### ISSUE TITLE
players see zero balance after rebuy until he refreshes the page

### ISSUE THREAD

**Issue by troggy** [acebusters/ab-web#699]
Sandbox v1.0.0_1505822706752

**Comment by sunify** [comment]
Probably will be fixed with https://github.com/acebusters/oracle-cashgame/pull/47

**Comment by troggy** [comment]
still relevant for 1.5.0

**Comment by troggy** [comment]
happened on 6max table with 3 players

**Comment by mateleshkavo** [comment]
I guess this one was fixed in the latest fix for v1.6, @sunify can you please confirm?

**Comment by sunify** [comment]
Nope, it still reproduces. Sometimes the player doesn't receive `Join` event on table contract and doesn't update the balance. Will try to fix it today

**Comment by sunify** [comment]
Not sure we are able to do smth about that. Looks like websocket skips frame sometimes
