### ISSUE TITLE
User is able to register account using previously registered email

### ISSUE THREAD

**Issue by mateleshkavo** [acebusters/ab-web#736]
**Steps to reproduce:**

1. Go to dapp.acebusters.com/register
2. Enter previously registered email.
3. Complete registration.

**Expected:**

1. Error message is shown: 'Email taken.'

**Actual:**

1. User is registered.

**Comment by sunify** [comment]
Fixed registration on staging. Can you verify?

**Comment by mateleshkavo** [comment]
Still can reproduce this issue and emails are still not getting delivered
